# Generated by Django 5.0.6 on 2024-10-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='events',
        ),
    ]
