# Generated by Django 5.0.6 on 2024-10-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
