
services:
  db:
    container_name: joinit-db
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
    image: postgres
    ports:
      - "5431:5432"
    networks:
      - default

      
  api:
    container_name: joinit-api
    build: joinit/.
    restart: always
    env_file:
      - ./.env
    environment:
      - SECRET_KEY:${SECRET_KEY}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
      - GOOGLE_CLIENT_ID:${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET:${GOOGLE_SECRET}
      - POSTGRES_HOST:db
    volumes:
      - ./joinit:/joinit
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - default

  #Nominatim:
  #  container_name: joinit-geo
  #  image: mediagis/nominatim:4.4
  #  restart: always
  #  ports:
  #    - "8001:8000"
  #  depends_on:
  #    - db
  #  networks:
  #    - default

  frontend:
    container_name: joinit-fe
    build: 
      context: ./joinit-fe
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./joinit-fe:/joinit
      - /joinit/node_modules
      - /joinit/.next
    command: npm run dev
    ports:
      - 3000:3000
      - 49153:49153
    depends_on:
      - api
    networks:
      - default

networks:
  default:
