
services:
  db:
    container_name: joinit-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres
    ports:
      - "5431:5432"
    networks:
      - default

      
  api:
    container_name: joinit-api
    build: joinit/.
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    volumes:
      - ./joinit:/joinit
      - ./emails:/app-emails
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
