
services:
  db:
    container_name: joinit-db
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
    image: postgres
    ports:
      - "5431:5432"
    networks:
      - default

      
  api:
    container_name: joinit-api
    build: joinit/.
    restart: always
    env_file:
      - ./.env
    environment:
      - SECRET_KEY:${SECRET_KEY}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_HOST:db
    volumes:
      - ./joinit:/joinit
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - default

  frontend:
    container_name: joinit-fe
    build: 
      context: ./joinit-fe
      dockerfile: Dockerfile
    restart: always
    command: npm run dev
    volumes:
      - ./joinit-fe:/joinit
      # Required to not break node modules.
      - /usr/src/web/node_modules
      # Required for next to do it's thing.
      - /usr/src/web/.next
    ports:
      - 3001:3000
    depends_on:
      - api
    networks:
      - default

networks:
  default:
