# Generated by Django 5.0.6 on 2025-01-05 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='joined_by',
            field=models.ManyToManyField(related_name='joined_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
