# Generated by Django 5.0.6 on 2025-01-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_joined_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.rating',),
        ),
    ]
