# Generated by Django 5.0.6 on 2025-01-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ratingproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingproxy',
            options={},
        ),
    ]
