# Generated by Django 5.0.6 on 2024-10-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rating_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
