# Generated by Django 5.0.6 on 2024-10-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_tags_remove_event_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='starting_ts',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ending_ts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sharable_link',
        ),
    ]
