# Generated by Django 5.0.6 on 2024-11-11 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_starting_ts_event_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(0, 'Commerciale'), (1, 'Culturale'), (2, 'Musica'), (3, 'Sportivo'), (4, 'Artistico'), (5, 'Storico'), (6, 'Educativo'), (7, 'Sanitario'), (8, 'Intrattenimento'), (9, 'Altro')], default=9), blank=True, null=True, size=None),
        ),
    ]
