# Generated by Django 5.0.6 on 2024-12-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Commerciale'), (1, 'Culturale'), (2, 'Musica'), (3, 'Sportivo'), (4, 'Artistico'), (5, 'Storico'), (6, 'Educativo'), (7, 'Sanitario'), (8, 'Intrattenimento'), (9, 'Altro')], default=9, null=True),
        ),
    ]
