# Generated by Django 5.0.6 on 2024-12-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_favorite'),
        ('events', '0012_event_cover_image_alter_event_tags'),
    ]

    operations = [
    ]
